### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by LucaColonnello** [petrides-anthony/social-api#1]
We want to build this type of feature https://tailwindcomponents.com/component/timeline

It's going to work in this way:
- user inputs his full name and logs in (no real auth for exercise purpose)
- user needs to be able to post a message (simple text)
- user needs to be able to comment on a post
- user needs to be able to like a post or a comment (showing the number of likes)

**Comment by LucaColonnello** [comment]
- Use parcel for client https://parceljs.org/
- Use MongoDB for data
- Use express for rest api
- Use redux for state
- Use react-router for views

**Comment by LucaColonnello** [comment]
## Data architecture

**Post Document**
```json
{
  "id": "ID",
  "user": "String",
  "content": "String",
  "likes": "Number",
  "timestamp": "Date",
  "parentId": "ID | null",
  "lastComment": {
     "user": "String",
     "content": "String"
   },
}
```

**Comment by LucaColonnello** [comment]
## API

- `GET /posts`: get all the posts
- `POST /posts`: add a new post
- `GET /posts/[id]/comments`: get all the comments for a post
- `POST /posts/[id]/comments`: add a comment to a post
- `POST /posts/[id]/like`: likes a post (which will work for posts and comment as they are the same identity)

**Comment by petrides-anthony** [comment]
![image](https://user-images.githubusercontent.com/25196139/85592809-65c72900-b63e-11ea-829e-fe6171f5112d.png)
